### ISSUE TITLE
Can't access any custom types 

### ISSUE THREAD

**Issue by dpersson9** [datocms/gatsby-source-datocms#10]
I'm using the following settings with the `gatsby-default-starter`, and have only added this plugin. 

```
   node -v 
   9.4.0

   npm -v
   5.6.0

   "gatsby": "^1.9.184",
   "gatsby-cli": "^1.1.28",
   "gatsby-source-datocms": "1.0.24",
```

However, I'm only getting the standard types, with no custom types at all. I have added the plugin to `gatsby-config` with the correct api token. It works without problems for my coworkers and to deploy to Netlify. For some reason it's not working locally for me.

**Comment by anthonysapp** [comment]
Something has definitely broken this recently. 
I just went through hell today figuring out which dependencies seem to have caused it - finally got it to work. 

```
node -v
8.9.4

npm -v
5.6.0

"dependencies": {
    "datocms-client": "0.3.40",
    "express-graphql": "0.6.6",
    "gatsby": "1.9.119",
    "gatsby-cli": "1.1.23",
    "gatsby-image": "1.0.27",
    "gatsby-link": "^1.6.28",
    "gatsby-plugin-netlify": "^1.0.12",
    "gatsby-plugin-react-helmet": "^1.0.8",
    "gatsby-source-datocms": "1.0.12",
    "gatsby-source-filesystem": "1.5.9",
    "gatsby-transformer-remark": "1.7.23",
    "graphql": "0.11.7",
    "graphql-relay": "0.5.1",
    "graphql-skip-limit": "1.0.7"
  }

I'll do some further investigation as to the root of this problem but for now that seems to be a working setup.
```

**Comment by matteoscurati** [comment]
Same error here.

`node -v`
`9.5.0`

**Comment by thetre97** [comment]
and again - 
```powershell
Windows 10
node -v 9.2.0
npm -v 5.6.0
Gatsby -v 1.1.25
```

**Comment by sioked** [comment]
I dug into the source to see if I could get this working without completely reverting back to old versions of each package.

It looks like the datocms-client repo has a breaking change to fetching all items. The issue seems like it's here: https://github.com/datocms/gatsby-source-datocms/blob/5774c7fa9c7e37908b54952deb7410558b4a037c/src/fetch.js#L6
I changed that to:
```js
client.items.all({}, { deserializeResponse: false, allPages: true }),
```
and was at least able to get the custom values back. However, after doing that I started getting a bunch of new errors with images: `DatoCmsAsset.resolutions field type must be Output Type but got: DatoCmsResolutions`. Temporarily I just commented out those types in extendAssetNode.js and could at least see my custom data types showing up in the graphiql instance. No idea about a fix for these errors yet, otherwise I would have opened a PR.

**Comment by stefanoverna** [comment]
Will look into this right away! Thanks for the report!

Il 12 feb 2018 23:04, "Ed Siok" <notifications@github.com> ha scritto:

**Comment by stefanoverna** [comment]
v1.0.26 should solve the issue!

**Comment by thetre97** [comment]
Don't know if its related, but I updated the plugin to v1.0.26, and it threw this error when I ran `gatsby develop`

```powershell
TypeError: Cannot read property 'replace' of undefined

  - index.js:10 module.exports
    [cirruscreative]/[slash]/index.js:10:13

  - create-file-path.js:38 module.exports
    [cirruscreative]/[gatsby-source-filesystem]/create-file-path.js:38:59

  - gatsby-node.js:61 Object.exports.onCreateNode
    G:/Projects/Cirrus Creative/cirruscreative/gatsby-node.js:61:19

  - api-runner-node.js:110 runAPI
    [cirruscreative]/[gatsby]/dist/utils/api-runner-node.js:110:36

  - api-runner-node.js:187
    [cirruscreative]/[gatsby]/dist/utils/api-runner-node.js:187:33

  - map.js:27
    [cirruscreative]/[async]/internal/map.js:27:9

  - eachOfLimit.js:64 replenish
    [cirruscreative]/[async]/internal/eachOfLimit.js:64:17

  - eachOfLimit.js:49 iterateeCallback
    [cirruscreative]/[async]/internal/eachOfLimit.js:49:17

  - onlyOnce.js:12
    [cirruscreative]/[async]/internal/onlyOnce.js:12:16

  - map.js:29
    [cirruscreative]/[async]/internal/map.js:29:13

  - util.js:16 tryCatcher
    [cirruscreative]/[bluebird]/js/release/util.js:16:23

  - nodeify.js:23 Promise.successAdapter
    [cirruscreative]/[bluebird]/js/release/nodeify.js:23:30

  - promise.js:566 Promise._settlePromise
    [cirruscreative]/[bluebird]/js/release/promise.js:566:21

  - promise.js:606 Promise._settlePromiseCtx
    [cirruscreative]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [cirruscreative]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [cirruscreative]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues
    [cirruscreative]/[bluebird]/js/release/async.js:17:14
```

gatsby-config contains these two source plugins:
```powershell
{
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: `gatsby-source-datocms`,
      options: {
        apiToken: `73e04028d2006169683ea79ff42849`,
      },
    }
```
And when I remove the `gatsby-source-filesystem` it still throws that error, however when i remove `gatsby-source-datocms` `gatsby develop` works fine..

**Comment by thetre97** [comment]
Ignore the above - I updated everything with `yarn upgrade` and then followed the example portfolio repo, and it all works fine... thanks!
