### ISSUE TITLE
tracedSVG background and color option.

### ISSUE THREAD

**Issue by oswaldoacauan** [datocms/gatsby-source-datocms#105]
Any plans to introduce background and color option for the traceSVG images?

```
fluid(maxWidth: 690, traceSVG: { color: "#FF5620", background: "#FFF" }) {
  ...GatsbyDatoCmsFluid_tracedSVG
}
```

**Comment by matjack1** [comment]
Not yet, but thanks for the suggestion, we have noted it in the feature requests!

**Comment by stefanoverna** [comment]
The v3 query should now support background images! https://github.com/datocms/gatsby-source-datocms#integration-with-gatsby-image
