### ISSUE TITLE
vipspng: libpng read error

### ISSUE THREAD

**Issue by KamilSlaweta** [datocms/gatsby-source-datocms#107]
There are some issue with gatsby builds when I am getting tracedSVG imgs. It is occurring randomly. Sometimes I am getting 1 error, other times there are 20 errors. (Generally I ma fetching about 200 imgs). 

err code: 
```
vipspng: libpng read error
1 | fragment GatsbyDatoCmsFluid_tracedSVG on DatoCmsFluid {
2 | tracedSVG
| ^
3 | aspectRatio
4 | src
5 | srcSet
6 | sizes
7 | }
```

**Comment by matjack1** [comment]
This is followed up here: https://community.datocms.com/t/gatsby-img/889/
