### ISSUE TITLE
Images don't have a `fluid` value

### ISSUE THREAD

**Issue by ndom91** [datocms/gatsby-source-datocms#118]
None of my images seem to have a `fluid` value.

For example, I have a content type called 'Partners' with a field 'Image' where I've uploaded some jpg's. 

Based upon the examples I would expect the following graphql query to return me a `gatsby-image` compatible `fluid` value when using the spread.

```graphql
{
  allDatoCmsLocation {
    nodes {
      image {
        fluid(maxWidth: 200, imgixParams: {fm: "jpg", auto: "compress"}) {
          ...GatsbyDatoCmsSizes
        }
      }
    }
  }
}
```

Even with some fields such as `src`, `srcSet`, `base64`, etc. instead of the `...GatsbyDatoCmsSizes` I receive no return values. Removing the fluid parameters (maxWidth, imgixParams) also has no effect unfortunately.

The return looks like such:

```graphql
{
  "data": {
    "allDatoCmsLocation": {
      "nodes": [
        {
          "image": {
            "fluid": null
          }
        },
        {
          "image": {
            "fluid": null
          }
        },
        {
          "image": {
            "fluid": null
          }
        },
        {
          "image": {
            "fluid": null
          }
        },
        {
          "image": {
            "fluid": null
          }
        },
        {
          "image": {
            "fluid": null
          }
        }
      ]
    }
  }
}
```

Am I missing something here?

**Comment by matjack1** [comment]
Thank you @ndom91 we can reproduce, I think it's a problem related to webp images. We are going to have a look and get back to you

**Comment by ndom91** [comment]
I thought for sure some of the uploads were .jpgs, does Dato convert them to webp on upload?

Anyway you're right, the results were all webp's, for example:

```graphql
{
  "data": {
    "allDatoCmsPartner": {
      "nodes": [
        {
          "image": {
            "fluid": null,
            "format": "webp",
            "path": "/30735/1593209744-huawei.webp"
          }
        },
        {
          "image": {
            "fluid": null,
            "format": "webp",
            "path": "/30735/1593209744-huawei.webp"
          }
        },
        {
          "image": {
            "fluid": null,
            "format": "webp",
            "path": "/30735/1593209728-decix.webp"
          }
        },
        {
          "image": {
            "fluid": null,
            "format": "webp",
            "path": "/30735/1593209728-decix.webp"
          }
        },
        {
          "image": {
            "fluid": null,
            "format": "webp",
            "path": "/30735/1593209711-eltek.webp"
          }
        },
        {
          "image": {
            "fluid": null,
            "format": "webp",
            "path": "/30735/1593209711-eltek.webp"
          }
        }
      ]
    }
  }
}
```

**Comment by matjack1** [comment]
images are left unchanged on upload. Then you can change the format by  passing some arguments to our API. But at the moment we have some problems with Webp source images. We can safely convert TO Webp, but we have issues converting FROM Webp.

We will check this and make sure it works though. We'll be in touch!

**Comment by stefanoverna** [comment]
Alright, webp images are now fully supported!
