### ISSUE TITLE
Incremental build warning: Invalid entity type item_type

### ISSUE THREAD

**Issue by chrisworman-pela** [datocms/gatsby-source-datocms#121]
I've noticed warning in my Gatsby Cloud build logs stating `Invalid entity type item_type`.  I have incremental builds enabled.  Here are the relevant build logs:

```
12:21:20 PM: success loading DatoCMS schema - 1.856s
12:21:20 PM: success createSchemaCustomization - 2.066s
12:21:20 PM: info Received update event for item_type 266102 from DatoCMS success loading DatoCMS content changes - 0.001s
12:21:20 PM: warning Invalid entity type item_type
```

This warning appears to be coming from the `gatsby-source-datocms` plugin.  I'm not sure if this is a problem with my web hook configuration or a bug in `gatsby-source-datocms`.  I've setup my Dato CMS web hooks according to instructions provided by @matjack1 (including a custom HTTP body):

![Screen Shot 2020-07-30 at 1 41 42 PM](https://user-images.githubusercontent.com/61762136/88972619-af70e800-d26a-11ea-9dd3-35dca47a770c.png)

**Comment by chrisworman-pela** [comment]
In case it helps, here is a screen shot of the logs from the Dato CMS dashboard of an example of an `item_type` event (this event is not necessarily the one correlated to the build warning in my original issue description ... I'm getting lots of these events as I enable "Publish/Draft" for the models in our Dato CMS repository). 

![Screen Shot 2020-07-30 at 2 11 57 PM](https://user-images.githubusercontent.com/61762136/88975389-f365ec00-d26e-11ea-8f23-6900b103ae26.png)

**Comment by stefanoverna** [comment]
That's because this plugin does not handle (yet) incremental updates for events: https://github.com/datocms/gatsby-source-datocms/blob/master/src/hooks/sourceNodes/index.js#L160

@ascorbic should we implement this?

**Comment by sidharthachatterjee** [comment]
@stefanoverna We should be able to pass in incremental updates for events. Let me know if you need any help here!

**Comment by matjack1** [comment]
I'm closing this now as it's very old. If someone needs it again, please reopen and we'll start investigating from scratch.
