### ISSUE TITLE
Opt out of `auto=format` for Gatsby Image Queries

### ISSUE THREAD

**Issue by jevenson** [datocms/gatsby-source-datocms#141]
See this discussion
https://community.datocms.com/t/turn-off-auto-webp-formatting-with-gatsby-source-datocms-with-gatsby-image/404/4

I'd like to take a stab at contributing to the plugin and submitting a PR. I was thinking of adding an argument that opts out of auto formatting, or disabling auto format when the imgix format (fm) parameter is provided.

Thoughts on either approach?

**Comment by stefanoverna** [comment]
Hi @jevenson! I'd rather take the second approach, that is disabling auto format when the imgix format (fm) parameter is provided. I've prepared 75adb243dbad with the change

**Comment by stefanoverna** [comment]
Released as https://github.com/datocms/gatsby-source-datocms/releases/tag/v2.5.13
