### ISSUE TITLE
Live reload not working on sandbox environments

### ISSUE THREAD

**Issue by anton-hc** [datocms/gatsby-source-datocms#142]
Have successfully forked the primary environment and am able to view the updated content from the sandbox environment.

However I cant get the live reload to work, the only way i can view the content changes made in Dato is to restart my local environment which is not ideal given the size of the project.

disableLiveReload is set to false

**Comment by stefanoverna** [comment]
You were right, thanks for noticing! The issue has been solved in v2.5.14 of this package!
