### ISSUE TITLE
Imgix auto format breaks PDFs/documents

### ISSUE THREAD

**Issue by claygiffin** [datocms/gatsby-source-datocms#145]
**Problem:** Automatically adding "auto=format" to every single asset URL by default causes PDFs to open as images instead of opening as pdfs, breaking old links and making pdf urls unusable.

**Solution:** First check whether "isImage" is true/false before applying auto format to the asset.

**Comment by stefanoverna** [comment]
Thanks for noticing @claygiffin! We just solved the issue in v2.5.15!
