### ISSUE TITLE
Migrating to gatsby-plugin-image with v3 release

### ISSUE THREAD

**Issue by theikid** [datocms/gatsby-source-datocms#147]
With Gatsby v3 release yesterday even if gatsby image is still supported, migration to gatsby-plugin-image should be done.

Is there any plan to migrate the datocms source plugin to use this new plugin ?

Thank you !

https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3

https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

**Comment by stefanoverna** [comment]
Absolutely! We'll work on this next week!

**Comment by vsimak** [comment]
@stefanoverna  Appreciate the responsiveness, really looking forward to seeing how the lighthouse metrics behave (on a large ecommerce gatsby website)!

**Comment by stefanoverna** [comment]
Alright, v2.6.2 should be Gatsby v3 ready! Here's how you can use the new `<GatsbyImage />` component!
