### ISSUE TITLE
Major Issue: build(...).toMap is not a function

### ISSUE THREAD

**Issue by dbismut** [datocms/gatsby-source-datocms#15]
Not sure what's happening, but when running `gatsby develop` I now get the following error:

<img width="468" alt="bug" src="https://user-images.githubusercontent.com/5003380/40229736-75a9a4da-5a95-11e8-9099-ee3b36aa903c.png">

I just tried creating a new project from scratch and the error is still there.
This seems to be linked to models that have an image field.

**Comment by matjack1** [comment]
I can confirm here that when I have pictures on Dato the build in Gatsby breaks with the same error

**Comment by stefanoverna** [comment]
What version of datocms-client do you have? 0.5.1+ should already solve the issue

**Comment by dbismut** [comment]
I'm not adding datocms-client explicitly, it's just the dependency version from gatsby-source-datocms.  In gatsby-source-datocms, package.json sets datocms-client version to `"datocms-client": ">=0.3.43"` (which I feel is not a super standard way of setting version dependency but I'm no expert). Anyway, this means that 0.5.1 is installed at the moment, and it does generate the error. If I manually revert it to 0.4.6, everything turns back to normal.

I've tried looking at the source code, it looks like your using `build` with the `image` fieldType in createAssetNode, when actually `fieldTypeParser[image]` doesn't exist.

Here is a longer stack trace in case it should help.
<img width="521" alt="stack trace" src="https://user-images.githubusercontent.com/5003380/40235806-ac3542b4-5aab-11e8-9b56-12efea4c17a6.png">

**Comment by stefanoverna** [comment]
gatsby-source-datocms@1.1.2 should solve the issue, can you confirm?

**Comment by matjack1** [comment]
it goes a bit deeper now, still broken here:

**Comment by dbismut** [comment]
Same thing here.

**Comment by mwickett** [comment]
I'm also seeing the same issue. Was getting the `.toMap` is not a function, upgraded to 1.1.2 and now seeing the `Cannot read property of 'format' of undefined`

**Comment by stefanoverna** [comment]
Sorry guys, gatsby-source-datocms@1.1.5 should solve the issue once and for all

**Comment by dbismut** [comment]
Indeed ;)

**Comment by matjack1** [comment]
Yay! It works :)
