### ISSUE TITLE
v2.6.2 forces to install gatsby-plugin-image which is not compativle with Gatsby v2

### ISSUE THREAD

**Issue by Chompas** [datocms/gatsby-source-datocms#150]
I've just updated to v2.6.2 but got the following error `Cannot find module 'gatsby-plugin-image/graphql-utils'`

I currently can't update to Gatsby v3 due to other dependency problems with Webpack 5 so I can't install `gatsby-plugin-image`

This should be treated as a breaking change instead.

**Comment by stefanoverna** [comment]
Hi @Chompas! The new v2.6.3 marks "gatsby-plugin-image" as an optional peer dependency, let me know if it solves your issues.

**Comment by Chompas** [comment]
Hi @stefanoverna It did solve it. Thanks!
