### ISSUE TITLE
SQIP image previews

### ISSUE THREAD

**Issue by Hless** [datocms/gatsby-source-datocms#153]
There is a gatsby transformer  that generates beautiful polygon SVG image previews as an alternative to the TracedSVG placeholder previews that come with the gatsby image plugins. (https://www.gatsbyjs.com/plugins/gatsby-transformer-sqip/) The plugin currently works with tranformer-sharp and contentful, but it does not work on datocms image fields, probably because it must be linked to the correct fields in dato. 

Would this be an interesting feature to have for dato? If so, could someone provide a pointer on where to look on how to implement this transformer. I could take a swing at it perhaps

**Comment by stefanoverna** [comment]
Closing this as it's quite stale.
