### ISSUE TITLE
Default focal point returns "null"

### ISSUE THREAD

**Issue by claygiffin** [datocms/gatsby-source-datocms#155]
When attempting to query an image that has not had its focal point deliberately set, Gatsby returns a null value instead of the default {x: 50, y: 50} that appears in DatoCMS's API explorer.

This can cause a build to break when querying x or y on a null object.

**Comment by stefanoverna** [comment]
Agreed! It's now implemented in v2.6.12 (focalPoint is still null for assets that are not images)
