### ISSUE TITLE
datoCmsSite queries return null

### ISSUE THREAD

**Issue by ivanovyordan** [datocms/gatsby-source-datocms#167]
I'm building a test blog and exploring the queries in the documentation. Everything works well so far except one thing.

Running this query in the CDA explorer works as expected:
``` graphql
query {
  _site {
    globalSeo {
      siteName
      titleSuffix
      twitterAccount
      facebookPageUrl
      fallbackSeo {
        title
        description
        image {
          url
        }
        twitterCard
      }
    }
  }
}
```
<img width="1025" alt="CDA" src="https://user-images.githubusercontent.com/979329/135520167-77ba4591-be6b-41c1-9ad7-b9d7515eebe7.png">

Running the query from the docs returns null.

``` graphql
query {
  datoCmsSite {
    globalSeo {
      siteName
      titleSuffix
      twitterAccount
      facebookPageUrl
      fallbackSeo {
        title
        description
        image {
          url
        }
        twitterCard
      }
    }
  }
}
```
<img width="1680" alt="Gatsby" src="https://user-images.githubusercontent.com/979329/135520626-3d40049b-77e9-4dc8-99c0-71def674f944.png">

What could be the reason for that behaviour in your opinion?

**Comment by stefanoverna** [comment]
Hi @ivanovyordan, I need some more info from you to assist:

* your package.json
* the name of your DatoCMS project

Thanks

**Comment by ivanovyordan** [comment]
Hey @stefanoverna, I was testing the beta version of Gatsby 4. When I downgraded back to version 3 it all worked well.

Thanks.
