### ISSUE TITLE
Object.entries and Object.assign are not compatible on IE11

### ISSUE THREAD

**Issue by dbismut** [datocms/gatsby-source-datocms#17]
Hi - I was testing a site on IE11 and got the following error popup:

<img width="461" alt="ie11" src="https://user-images.githubusercontent.com/5003380/40605280-20068f50-6262-11e8-958b-109da34548ee.png">

Looks like `Object.entries` and `Object.assign` are not available on IE11, and you're using these methods on these lines:

https://github.com/datocms/gatsby-source-datocms/blob/8e14eb8920d95383cecb333a9ffd53c482f3a263/src/index.js#L13
https://github.com/datocms/gatsby-source-datocms/blob/8e14eb8920d95383cecb333a9ffd53c482f3a263/src/index.js#L15

I'm far from a pro, but I think you should consider including [Object assign](https://babeljs.io/docs/plugins/transform-object-assign/) and [Object entries](https://babeljs.io/docs/plugins/transform-object-entries/) polyfills for babel, or even the more [generic polyfill](https://babeljs.io/docs/plugins/transform-runtime/) into your `.babelrc` json file.

**Comment by stefanoverna** [comment]
Thanks for reporting, fixed in gatsby-source-datocms@1.1.6
