### ISSUE TITLE
GraphQL should expose original Id

### ISSUE THREAD

**Issue by dbismut** [datocms/gatsby-source-datocms#18]
I think it would be cool if gatsby-source-datocms would expose the real id (without prefixes or suffixes). Not saying it should replace the id attribute, but maybe adding a `originalId` field or something would be useful (at least in my use case where I need to reconcile with `datocms-client`).

**Comment by stefanoverna** [comment]
Agreed!

Il lun 4 giu 2018, 18:37 David <notifications@github.com> ha scritto:
