### ISSUE TITLE
Stuck on "Loading DatoCMS content" since 3.0.0

### ISSUE THREAD

**Issue by NSpehler** [datocms/gatsby-source-datocms#183]
Hello there 👋

I'm having a really strange issue since upgrading from 2.6.18 to 3.0.0 (and I've tried every version including 3.0.12 without luck).

My `gatsby develop` gets stuck `loading DatoCMS content` and systematically times out after 50 minutes (usually this step takes around 1 minute on 2.6.18).

```
success open and validate gatsby-configs, load plugins - 1.940s
success onPreInit - 0.007s
success initialize cache - 0.166s
success copy gatsby files - 0.264s
success Compiling Gatsby Functions - 0.342s
success onPreBootstrap - 0.385s
success loading DatoCMS schema - 1.786s
success createSchemaCustomization - 1.951s
not finished source and transform nodes - 2892.997s
not finished loading DatoCMS content - 2892.844s
```

Here are a few things I tried without luck:
- Removing all `createPage` statements in `gatsby-node.js` except my homepage
- Using npm instead of yarn
- Fresh install of `node_modules` and `yarn.lock`
- Removing all plugins in `gatsby-config.js` except `gatsby-source-datocms`
- Using `gatsby develop --verbose` but doesn't show any more information

I don't really know what else to try because there's no error or warning... Note that `gatsby build` is stuck as well.

For reference here are my Gatsby plugins versions in `package.json`:
```
{
    "gatsby": "^4.4.0",
    "gatsby-background-image": "^1.5.3",
    "gatsby-image": "^3.11.0",
    "gatsby-plugin-create-client-paths": "^4.4.0",
    "gatsby-plugin-gatsby-cloud": "^4.4.0",
    "gatsby-plugin-image": "^2.4.0",
    "gatsby-plugin-manifest": "^4.4.0",
    "gatsby-plugin-offline": "^5.4.0",
    "gatsby-plugin-react-helmet": "^5.4.0",
    "gatsby-plugin-react-helmet-canonical-urls": "^1.4.0",
    "gatsby-plugin-react-svg": "^3.0.0",
    "gatsby-plugin-robots-txt": "^1.6.14",
    "gatsby-plugin-sass": "^5.4.0",
    "gatsby-plugin-sharp": "^4.4.0",
    "gatsby-plugin-sitemap": "^5.4.0",
    "gatsby-plugin-smoothscroll": "^1.2.0",
    "gatsby-source-datocms": "^3.0.12",
    "gatsby-transformer-remark": "^5.4.0",
    "gatsby-transformer-sharp": "^4.4.0",
}
````

Do you have any ideas, or maybe some more troubleshooting steps I should try?

Thank you so much for your help,
Nicolas

**Comment by anshumansworld** [comment]
@NSpehler any luck?

**Comment by Pierregadait** [comment]
@anshumansworld  I am having the same issue, any help on how to resolve this?
