### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by anshumansworld** [datocms/gatsby-source-datocms#185]
I'm getting the following error:
```
"gatsby-source-datocms" threw an error while running the sourceNodes lifecycle:

invalid json response body at https://site-api.datocms.com/docs/site-api-hyperschema.json reason: Unexpected end of JSON input
```

**Configuration:**
Node v14.18.3
npm 6.14.15
Gatsby CLI version: 4.5.1
Gatsby version: 3.6.2

<img width="1151" alt="Screen Shot 2022-01-15 at 8 25 31 PM" src="https://user-images.githubusercontent.com/1582526/149626373-d56d8212-2823-4892-b0a1-e72b9ad45392.png">

**Comment by stefanoverna** [comment]
This was probably a temporary network issue
