### ISSUE TITLE
Get base64 code for image

### ISSUE THREAD

**Issue by maximeealet** [datocms/gatsby-source-datocms#190]
Hi there, 

I need for a project to get the base64 code of an image I upload on DatoCMS. In the Graphql schema base64 is only for blurred image placeholder. 

I tried using a resolver to access to the image url and convert it in javascript with no luck as the url field doesn't seem to be accessible by the source arg in my resolve function. 

Would you have any lead I could follow to perform this at build time instead of retrieving the url as usual and convert directly inside my page ?

Thanks in advance !

**Comment by matjack1** [comment]
Very sorry @maximeealet for forgetting this issue, but maybe it can still be useful to someone else.

Maybe this has changed since your question, but if I've understood correctly, you can get this information from an asset by querying:

```
resolutions {
    base64
}
```
