### ISSUE TITLE
Entity Ids reveal use of DatoCms

### ISSUE THREAD

**Issue by joernroeder** [datocms/gatsby-source-datocms#191]
I'm currently looking into attack vectors for our systems and noticed that all enityIds are prefixed with `DatoCms`.
https://github.com/datocms/gatsby-source-datocms/blob/6d6bd50ebf349c1f76684a8f5dbf3375a2cac28f/src/hooks/sourceNodes/index.js#L87

I think this could be an easy change, allowing me to pass in my own prefix via the plugin options and fall back to the current behavior if the option isn't used. I know that the moment I serve assets from dato the domain `datocms-assets.com` get's exposed as well, but this seems avoidable by using our own [Amazon AWS S3 Storage](https://www.datocms.com/marketplace/enterprise/aws-s3)

**Comment by matjack1** [comment]
Hey @joernroeder but are node names exposed in the final build? Aren't only available in the development phase?

**Comment by stefanoverna** [comment]
Closing for now, feel free to reopen
