### ISSUE TITLE
Localized results appear when content is untranslated

### ISSUE THREAD

**Issue by byronwilliams** [datocms/gatsby-source-datocms#192]
The plugin makes all of the site's locales available for every piece of content, regardless of whether it's been translated or not. This makes it hard to work out if a translation for a piece of content really exists or not.

For example if the content is in English (UK) as shown here:

![image](https://user-images.githubusercontent.com/303604/162419180-7ab110ca-adcb-4401-be47-d9b80450de70.png)

And I have both English and German enabled then I can query for both English and German versions, even though no translation actually exists for German.

```graphql
query GetAllProductReviews {
  allDatoCmsStartDesign(filter: {locale: {in: ["de-DE", "en-GB"]}}) {
    nodes {
      locale
      id
      meta {
        isValid
        status
      }
    }
  }
}
```

```json
{
  "data": {
    "allDatoCmsStartDesign": {
      "nodes": [
        {
          "locale": "en-GB",
          "id": "DatoCmsStartDesign-115171229-en-GB",
          "meta": {
            "isValid": true,
            "status": "published"
          }
        },
        {
          "locale": "de-DE",
          "id": "DatoCmsStartDesign-115171229-de-DE",
          "meta": {
            "isValid": true,
            "status": "published"
          }
        }
      ]
    }
  }
}
```

This should only return the English (UK) version

```json
{
  "data": {
    "allDatoCmsStartDesign": {
      "nodes": [
        {
          "locale": "en-GB",
          "id": "DatoCmsStartDesign-115171229-en-GB",
          "meta": {
            "isValid": true,
            "status": "published"
          }
        }
      ]
    }
  }
}
```

The [documentation](https://github.com/datocms/gatsby-source-datocms/#localized-fields) suggests that I can test for the presence of a field to determine whether the content exists or not. This isn't as helpful as not having the document there in the first place because it's not translated.

Can we add an option to only create pages for locales that have been translated?

**Comment by stefanoverna** [comment]
Please try experimental version "4.0.0-0" of this package to see if it solves your issue, thanks!

**Comment by stefanoverna** [comment]
released as v4.0.0

**Comment by byronwilliams** [comment]
I've just tested this with v4.0.0 but I actually get no localized data back at all. 

![Screenshot from 2022-04-22 09-31-36](https://user-images.githubusercontent.com/303604/164650307-2545f609-ba31-4c1e-8c85-38e70dee1fab.png)

As per my original screenshot I definitely have content for my start_design model.

These queries worked with v3.0.19

Let me know what info I can provide to assist

**Comment by byronwilliams** [comment]
v4:
info Total nodes: 665, SitePage nodes: 3 (use --verbose for breakdown)

v3: 
info Total nodes: 3003, SitePage nodes: 46 (use --verbose for breakdown)

**Comment by stefanoverna** [comment]
Please try v4.0.1! Thanks for the feedback!

**Comment by byronwilliams** [comment]
This is working correctly now. Thanks for fixing it.
