### ISSUE TITLE
Empty Field Throws Invariant Violation

### ISSUE THREAD

**Issue by benforshey** [datocms/gatsby-source-datocms#2]
```JSON
dependencies": {
    "gatsby": "^1.9.149",
    "gatsby-source-datocms": "1.0.16"
...
}
```
Hi, DatoCMS team. I really enjoy using your CMS with Gatsby! I've run into a problem where an empty field (in my case, a multiple links field called "related") within the DatoCMS admin area will throw an error in Gatsby:
```javascript
Invariant Violation: Encountered an error trying to infer a GraphQL type for: "related___NODE".   There is no corresponding node with the id field matching: "null"
```

I'd love to be able to leave this multiple links field blank, as I'm using it to link related articles that I write, and there isn't always a related article to which I should link. 

I did some searching around and [found an error](https://github.com/gatsbyjs/gatsby/issues/1517) with the gatsby-source-contentful plugin that seems to be pretty similar.

**Comment by stefanoverna** [comment]
Hi @benforshey, thanks for reporting. I'll take a look at the `setFieldsOnGraphQLNodeType` action on GatsbyJS and see if we can fix the issue.

**Comment by jesperkc** [comment]
Any news on this?

**Comment by stefanoverna** [comment]
Unfortunately not :( Closing this one in favour of https://github.com/datocms/gatsby-source-datocms/issues/11
