### ISSUE TITLE
media asset default alt and title not respected

### ISSUE THREAD

**Issue by dw-srohrlack** [datocms/gatsby-source-datocms#200]
The default alt and title text of media assets is not being respected in different locales.

Scope: potentially all references to datocms assets

Steps to reproduce:

1. add a default alt- and title-text in multiple locales for a media asset in the asset manager
2. create a model that uses a localised media field and a localised modular content field and create a block for that modular content which has a "media" field
3. create a record that uses the aforementioned asset in the image field and modular content block's image field - but don't define a specific alt- and title-text
4. query the record via the gatsbyjs graphql interface, try out different locales

Expected result: the alt- and title-text of the asset is localised based on the requested locale

Result: the alt- and title-text are not using the respective default values for the respective locale

Tested plugin versions: 4.0.4

**Comment by stefanoverna** [comment]
Hello @dw-srohrlack... version 4 is known to have problems with localization. We're working on a new version of this plugin that should solve all the issues, and [introduce more flexibility](https://github.com/datocms/gatsby-source-datocms/tree/experiment#localized-fields).

You can try it installing `gatsby-source-datocms@next` on your project — but it must be upgraded to gatsby 4.24.0!

**Comment by dw-srohrlack** [comment]
Hi @stefanoverna , downgrading to 3.0.19 seems to have fixed the issue. I can't find much details in the releases regarding what's different in v4 except it produces less graphql nodes - am I fine with running v3 until we get around to upgrading to v5?

**Comment by stefanoverna** [comment]
If you're satisfied with 3.0.19.. than stick with 3.0.19 :) 

Here's what changes in v5: https://www.datocms.com/product-updates/new-gatsby-source-plugin-faster-build-times
