### ISSUE TITLE
Plugin doesn't work with Gatsby v5

### ISSUE THREAD

**Issue by matheusml** [datocms/gatsby-source-datocms#206]
<img width="769" alt="Screenshot 2022-11-29 at 16 33 07" src="https://user-images.githubusercontent.com/444202/204630438-5688fa31-9fa4-496e-95f9-c159022caec1.png">

Do you have any plans on updating it?

**Comment by theikid** [comment]
Hi there, trying to install an other Gatsby plugin it breaks because of Dato dependencies. Any way to correct this ? Thank you !

**Comment by stefanoverna** [comment]
@theikid can you please provide more information? How is it breaking?

**Comment by theikid** [comment]
> @theikid can you please provide more information? How is it breaking? What's the other Gatsby plugin?

I'm on the latest gatbsy version '5.2.0' and I got this when running install of the package. 

`Could not resolve dependency:
npm ERR! peer gatsby@"^2.12.1 || ^3.0.0 || ^4.0.0" from gatsby-source-datocms@4.0.5
npm ERR! node_modules/gatsby-source-datocms
npm ERR!   gatsby-source-datocms@"*" from the root project`

**Comment by stefanoverna** [comment]
Can you please try installing gatsby-source-datocms v5.0.1?

**Comment by theikid** [comment]
> Can you please try installing gatsby-source-datocms v5.0.1?

I manage to install it without issue. But now I got this error with my query

`./src/pages/index.js?export=default
Error: /Users/maximeealet/Desktop/FrontDev/onefirst-signature_form/src/pages/index.js: BabelPluginRemoveGraphQLQueries: GraphQL syntax error in query:

    allDatoCmsBanner {
    nodes {
      banner {
        url
        height
        width
      }
      name
    }
  }
   
message:

Syntax Error: Unexpected Name "allDatoCmsBanner".

GraphQL request:2:5
1 |
2 |     allDatoCmsBanner {
  |     ^
3 |     nodes {`

**Comment by stefanoverna** [comment]
Are you able to share a repo reproducing the issue @theikid?

**Comment by maximeealet** [comment]
> Are you able to share a repo reproducing the issue @theikid?

Hi there, here is the page with the error. It's just the GraphQL query. 
https://github.com/maximeealet/onefirst-signature_generator/blob/main/src/pages/index.js
