### ISSUE TITLE
Locale at query level returns wrong fields

### ISSUE THREAD

**Issue by jgdemattos** [datocms/gatsby-source-datocms#209]
Issue when querying a document with the locale argument at **document level**, like the the query below:

```
query BlogPostByOriginalId($language: String!, $originalId: String!) {
  datoCmsBlogpost(originalId: {eq: $originalId}, locale: $language) {
    originalId
    title
  }
}
```
This query will, **sometimes**, ramdomly return fields in the wrong language when building the site.  This happens mostly in production.

As an example, if the _$language_ is PT, portuguese, I will get fields in EN, english. 

The safe way to ensure the correct field language, is to use the locale argument at field level, like below:

```
query BlogPostByOriginalId($language: String!, $originalId: String!) {
  datoCmsBlogpost(originalId: {eq: $originalId}, locale: $language) {
    originalId
    title(locale: $postLang)
  }
}
```

**Comment by vanska** [comment]
I'm facing the same issue. Works as intended in development.

**Comment by Faxxiz** [comment]
Facing the same issue, not on a development but on every build.

```
export const pageQuery = graphql`
  query HomePage($locale: String!) {
    datoCmsGlobalConfiguration(locale: $locale) {
      id
      websiteName
      ...CookiesBannerFields
    }
  }
`
```

here is my gatsby-node just to show that I'm creating the same page on different languages :
```
async function generateHomePage() {
  const index = path.resolve(`./src/templates/index.tsx`)

  allLocales.data.datoCmsSite.locales.forEach(locale => {
    createPage({
      path: locale === defaultLocale ? "/" : `/${locale}`,
      component: index,
      context: {
        locale,
        defaultLocale,
        slugs: allMainSlugs,
      },
    })
  })
}
```

and as you can see in my context the locale is "fr" and the data returned is in english

![Capture d’écran du 2022-12-29 10-04-14](https://user-images.githubusercontent.com/27006831/209929100-5ab10260-7dcb-44a0-bdf7-1558f71c14e2.png)

**Comment by pieh** [comment]
Hey folks, I opened PR with potential fix for those issues in https://github.com/datocms/gatsby-source-datocms/pull/211
