### ISSUE TITLE
Failing with Gatsby v5 and node 18.13.0

### ISSUE THREAD

**Issue by donaldboulton** [datocms/gatsby-source-datocms#212]
This package is failing with Gatsby v5 and node 18.13.0. It even state so on your read me and at NPM

**Comment by sistrall** [comment]
Hi @donaldboulton,

could you please provide more details? Any info in the stacktrace?

**Comment by matjack1** [comment]
Hey @donaldboulton I'm going to close this for now as we were getting segmentation faults, something that seems due to NodeJS rather than our code.

But if you have more details, please update this issue. Thank you
