### ISSUE TITLE
Request for Contributing Guidelines

### ISSUE THREAD

**Issue by mordonez** [datocms/gatsby-source-datocms#214]
Hello @stefanoverna,

I hope this message finds you well. I am interested in contributing to the project, but I noticed that there is no `CONTRIBUTING.md` file in the repository that outlines the contribution process.

Would it be possible to add a `CONTRIBUTING.md` file to the repository? This file would greatly help new contributors like myself understand how they can contribute to the project.

Well, thank you for your time and consideration.

**Comment by sistrall** [comment]
Hi @mordonez :-)

Thanks for reaching out: contributions and fixes are always welcome.

I added a (very basic at the moment) [CONTRIBUTING](https://github.com/datocms/gatsby-source-datocms/blob/master/CONTRIBUTING.md) file.

Is there anything specific you'd like to know?

**Comment by stefanoverna** [comment]
I'm gonna close this for now, feel free to reopen @mordonez!
