### ISSUE TITLE
Missing version 5.1.0 Change Log

### ISSUE THREAD

**Issue by arsinclair** [datocms/gatsby-source-datocms#217]
Hello,

I noticed `npm outdated` indicates that a new version is available - `5.1.0`, however the neither CHANGELOG.md, nor the 5.1.0 tag contain a description of the changes. The release on the Releases page is also missing.

As I would like to keep my dependencies up to date, I would like to upgrade, but I don't know what's changing. It would be much appreciated if the Change Log is updated along with the new releases.

**Comment by stefanoverna** [comment]
Something went wrong with our Releases page, thanks for noticing.

**Comment by arsinclair** [comment]
Thank you for the resolution.
