### ISSUE TITLE
Fetching all locales of the record

### ISSUE THREAD

**Issue by hrumhurum** [datocms/gatsby-source-datocms#221]
Currently there is a way to fetch all locales of the field:

```
query {
  allBlogPosts {
    _allTitleLocales {
      locale
      value
    }
  }
}
```

But how to fetch all locales of the record? Something like this would be helpful:

```
query {
  _allBlogPostLocales {
      locale
      title
      slug
      ...
  }
}
```

With `gatsby-source-datocms` version 4.x it was possible to achieve this with:

```
query {
  allDatoCmsBlogPosts {
    nodes {
      locale
      title
      slug
      ...
    }
  }
}
```

but this approach no longer works in `gatsby-source-datocms` 5.x.

**Comment by stefanoverna** [comment]
On our native CDA we have [`_locales`](https://www.datocms.com/docs/content-delivery-api/localization#get-the-localizations-available-for-a-record). We should add it to the Gatsby plugin as well!

**Comment by hrumhurum** [comment]
I cannot see a way to achieve the desired result using a single GraphQL query given the existing capabilities of CDA. Only by manual iteration or by manual composition of the resulting objects from the field pieces retrieved by https://www.datocms.com/docs/content-delivery-api/localization#fetching-all-localizations which is quite a challenge to be honest.

**Comment by stefanoverna** [comment]
With CDA, this would work right?

```
query {
  itBlogPosts: allBlogPosts(filter: {_locales: {allIn: [it]}}, locale: it) {
    title
  }
  enBlogPosts: allBlogPosts(filter: {_locales: {allIn: [en]}}, locale: en) {
    title
  }
  ...
}
```

**Comment by hrumhurum** [comment]
Right, that would work if one hardcodes the locales beforehand. However, this approach is only a hacky workaround. For the time being, I reverted the project to `gatsby-source-datocms` v4.0.5 to avoid the situation altogether until something better becomes available.

**Comment by souljuse** [comment]
> But how to fetch all locales of the record? 

As Stefano was pointing out. You can fetch all locales in a record by this by using `locale`. It returns an array of locales used in the record. For example if you run this query

```
query {
  localesQuery: allDatoCmsBlogPosts {
    nodes {
      locales
    }
  }
}
```

Will result in 

```
  "data": {
    "localesQuery": {
      "nodes": [
        {
          "locales": [
            "en",
          ],
        },
      ],
    },
```

You can also get all localized content for a certain locale by using filters. 

```
query {
  itBlogPosts: allBlogPosts(filter: {locales: {in: ["it"]}}, locale: "it") {
    title
  }
}
```

``` {
  "data": {
    "itResults": {
      "nodes": [
        {
          "title": "Italian title",
        },
      ],
    },
  },
}
```
>this approach is only a hacky workaround

We know it is not ideal, but for the moment we prefer to keep it coherent with the CDA :) Sorry for the inconvenience.
