### ISSUE TITLE
How to use near query

### ISSUE THREAD

**Issue by anshumansworld** [datocms/gatsby-source-datocms#224]
Is it possible to use `near` filter on location data?

e.g. `filter: {location: {near: {latitude: "", longitude: "", radius: ""}}}`

**Comment by marcelofinamorvieira** [comment]
Hello @anshumansworld you can do them as such: https://www.datocms.com/docs/content-delivery-api/filtering-records#lat_lon 

The radius is specified in meters, forming a circle with the central point being the latitude and longitude you specified

**Comment by anshumansworld** [comment]
The question was related to gatsby plugin. How can I do the same in gatsby plugin?
