### ISSUE TITLE
Inverse relationships support

### ISSUE THREAD

**Issue by mordonez** [datocms/gatsby-source-datocms#225]
### Context
Currently, the [Inverse relationships](https://www.datocms.com/docs/content-delivery-api/inverse-relationships) functionality is not supported in the [gatsby-source-datocms](https://github.com/datocms/gatsby-source-datocms/) plugin. This feature is available in the Content Delivery API and can be utilized by migrating to the [gatsby-source-graphql](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-graphql) plugin. However, I believe that integrating inverse relationships directly into the plugin would be a valuable addition.

### Request
We kindly request the addition of support for Inverse relationships in the source plugin. This would provide a seamless experience for users of DatoCMS who rely on this feature with Gatsby, without the need to switch to a different plugin.

### Roadmap and Plans
Is it on the roadmap? Knowing this would help us plan our upcoming projects more effectively

**Comment by claygiffin** [comment]
@marcelofinamorvieira Is there any update on when this might be available for use?
