### ISSUE TITLE
TIFF issues with Gatsby Image

### ISSUE THREAD

**Issue by claygiffin** [datocms/gatsby-source-datocms#227]
TIFF images are not displayed when using `gatsby-plugin-image`. This is because the `<source>` elements have their `type` attribute set to `type="image/tif"`. This attribute is actually incorrect because we are using imgix's auto-formatting capabilities to serve up a browser-compatible image to the user. If I remove that attribute via inspector, the image displays correctly.

I need some way to either disable the `type` attribute or have it display the correct data.

Additionally, is there a reason that TIFF images use the `<picture>` element rather than the `<img>` tag that pngs or jpgs use? Or is that decided by `gatsby-plugin-image`?

**Comment by matjack1** [comment]
hey @claygiffin thank you for the report. We are going to have a look and we'll get back to you

**Comment by stefanoverna** [comment]
@claygiffin v5.1.4 should fix the issues, thanks for reporting!
