### ISSUE TITLE
video_3

### ISSUE THREAD

**Issue by jesperkc** [datocms/gatsby-source-datocms#23]
Hi

I'm wondering why images from DatoCms in GraphQL are type *DatoCmsAsset* but videos are *video_1*, *video_2* etc...
Shouldn't they be DatoCmsVideo or at least DatoCmsAsset?

**Comment by matjack1** [comment]
@jesperkc videos are now of type `DatoCmsVideoField`, which I think it's better than before.

I'm going to close the issue but if you still have any feedback feel free to comment or reopen. Thanks!
