### ISSUE TITLE
TypeError: Site is not a constructor

### ISSUE THREAD

**Issue by jarred** [datocms/gatsby-source-datocms#27]
I get this error with a vanilla gatsby project, using the latest version of this plugin.

```js
error Plugin gatsby-source-datocms returned an error
  TypeError: Site is not a constructor
  - createSiteNode.js:15 module.exports
    [gatsby-source-datocms]/createSiteNode.js:15:14
```

if I dig into `createSiteNode.js` the variable `Site` (used on line 15) is undefined. Both `siteEntity` and `itemsRepo` used in the constructor seem to be correct.

Is this an issue with `datocms-client` or this packages usage of it?

**Comment by stefanoverna** [comment]
Thanks for the report @jarred, fixed in v1.1.14
