### ISSUE TITLE
Traced SVG images

### ISSUE THREAD

**Issue by sedubois** [datocms/gatsby-source-datocms#29]
Is there any way to add `tracedSVG` to the [image fragments](https://github.com/datocms/gatsby-source-datocms/blob/7a8b133792023acaaa4345b601de67732b3df887/src/assetFragments.js), similar to what is done in [gatsby-source-contentful](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/fragments.js#L14)?

I also think that the sizes/resolutions terminology should be changed to fluid/fixed.

**Comment by stefanoverna** [comment]
Added in version `2.1.0-beta.1`, soon to be released! 

https://github.com/datocms/gatsby-source-datocms/blob/2.1.0/CHANGELOG.md#v210
