### ISSUE TITLE
Gatsby data empty after datocms installation

### ISSUE THREAD

**Issue by jacenre** [datocms/gatsby-source-datocms#30]
### Issue

When doing `gatsby develop`, it prints the following error in the console
```
GraphQL Error Unknown field `content` on type `[tags_2]`

  file: C:/Users/<USER>/Documents/gatsby/project/.cache/fragments/datocms-seo-fragments.js

   1 |
   2 |   fragment GatsbyDatoCmsSeoMetaTags on DatoCmsSeoMetaTags {
   3 |     tags {
   4 |       tagName
>  5 |       content
     |       ^
   6 |       attributes {
   7 |         property
   8 |         content
   9 |         name
  10 |       }
  11 |     }
  12 |   }
  13 |
```

After which, the project gets compiled successfully. 
When loading the page though, it gives an error which described that the data object passed through in `const Layout =  ({ children, data }) => (` is undefined.
```
TypeError: Cannot read property 'site' of undefined
new Layout
C:/Users/<USER>/Documents/gatsby/version-test/src/layouts/index.js:11
   8 | const Layout = ({ children, data }) => (
   9 |   <div>
  10 |     <Helmet
> 11 |       title={data.site.siteMetadata.title}
  12 |       meta={[
  13 |         { name: 'description', content: 'Sample' },
  14 |         { name: 'keywords', content: 'sample, something' },
View compiled
▶ 49 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
```
### How to replicate the issue

1. Create a new project
``` gatsby new project ```
2. Install gatsby-source-datocms
``` npm install --save gatsby-source-datocms ```
3. Add gatsby-source-datocms to gatsby-config.js (I changed the apiToken to my own)
```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-datocms`,
      options: {
        apiToken: "PUT YOUR API TOKEN HERE",
      },
    },
  ],
}
```
### Noteworthy stuff

- All queries still work in the localhost:8000/___grapql IDE, just the data object passed inside the layout page is undefined.
- Data is only undefined after adding gatsby-source-datocms to gatsby-config.js
- gatsby-config.js is in the root folder, not in the src/ folder.

**Comment by matjack1** [comment]
I cannot replicate anymore with current version of Gatsby and gatsby-source-datocms.

I'm going to close this, but feel free to reopen if you can still reproduce.
