### ISSUE TITLE
Fetch all the localized values for a field

### ISSUE THREAD

**Issue by sedubois** [datocms/gatsby-source-datocms#32]
I'm trying to make use of the `_all<FieldName>Locales` property which was recently introduced and announced in this post:
https://www.datocms.com/changelog/fetch-all-the-language-values-for-a-field-in-a-sing/

The field is available on the DatoCMS GraphQL API, e.g. I have a type called Posts and I can query allPosts { _allSlugLocales { value } }, but as discussed with @stefanoverna `gatsby-source-datocms` needs to be updated to expose this too.

I need this to implement a language switcher which preserves the location on the website (paths are based on localized slugs).

**Comment by sedubois** [comment]
Will gatsby-source-datocms still be maintained or should we be using gatsby-source-graphql? Does it offer the same features?

**Comment by stefanoverna** [comment]
Added in version `2.1.0-beta.1`, soon to be released! 

https://github.com/datocms/gatsby-source-datocms/blob/2.1.0/CHANGELOG.md#v210
