### ISSUE TITLE
Union types don't work

### ISSUE THREAD

**Issue by sedubois** [datocms/gatsby-source-datocms#33]
I have a type `Page` which has a field `content` which links to various other types like `Post`, `Recipe`, `NavPage` etc. The native DatoCMS GraphQL API works OK, but the one generated by `gatsby-source-datocms` does not, it throws errors such as `Expected value of type \"DatoCmsNavPage\" but got: [object Object].` when querying for some sub-properties of `content`.

Is this supposed to work or is this a feature which could be added?

I am now blocked with content modeling with DatoCMS and Gatsby as it appears that these 3 features are missing:
- deep filtering (#34)
- union types (this bug)
- interface types (https://github.com/datocms/feature-requests/issues/95)

`Page` content model:

<img width="677" alt="screen shot 2018-10-07 at 14 26 04" src="https://user-images.githubusercontent.com/4217871/46581193-f873fe80-ca3c-11e8-9a46-82bb173b645c.png">

DatoCMS GraphQL API, works OK:

<img width="1435" alt="screen shot 2018-10-07 at 14 27 24" src="https://user-images.githubusercontent.com/4217871/46581208-4f79d380-ca3d-11e8-8e9b-3c1abd477b59.png">

Gatsby GraphQL API, doesn't work:

<img width="1435" alt="screen shot 2018-10-07 at 14 25 02" src="https://user-images.githubusercontent.com/4217871/46581189-d37f8b80-ca3c-11e8-83c0-412ad8a8dc24.png">

**Comment by sedubois** [comment]
The error is basically the same as described in [this issue](https://github.com/gatsbyjs/gatsby/issues/6443) which was fixed in the v2 beta, but I observe this with Gatsby v2.0.14.

**Comment by stefanoverna** [comment]
Solved in version `2.1.0-beta.1`, soon to be released! 

https://github.com/datocms/gatsby-source-datocms/blob/2.1.0/CHANGELOG.md#v210
