### ISSUE TITLE
Deep filtering doesn't work

### ISSUE THREAD

**Issue by sedubois** [datocms/gatsby-source-datocms#34]
Let's say I have a type `Post` which has a property `category` of type `PostCategory`, which itself has a property `seo` of type `SEO`. Currently it is not possible to filter by an SEO property, e.g. `allDatoCmsPost(filter: { category: { seo: { title: { eq: "my-title" } } } })`.

The reason that in this example I offload various properties of the `PostCategory` model onto a separate `SEO` model is because there's currently no GraphQL interface type available (see https://github.com/datocms/feature-requests/issues/95) and I don't want to replicate all my SEO properties across all objects. And I can't use `_seoMetaTags` because they don't seem to share a common type definition either.

**Comment by matjack1** [comment]
We agree that this would be very useful, but now this is blocked by:

https://github.com/datocms/product-roadmap/issues/128

**Comment by matjack1** [comment]
We are tracking this feature request here now: https://community.datocms.com/t/deep-filtering-on-both-cma-and-cda/291

I'm closing this for now as we use Community as a centralised place to inform our priorities.
