### ISSUE TITLE
conflicting field types in field types

### ISSUE THREAD

**Issue by trickydisco78** [datocms/gatsby-source-datocms#37]
I've got 2 separate content models that use default values. When using gatsby i'm getting the following

```
`warning There are conflicting field types in your data. GraphQL schema will omit those fields.
DatoCmsField.defaultValue:
 - type: boolean
   value: false
 - type: string`
```

**Comment by stefanoverna** [comment]
Solved in version `2.1.0-beta.1`, soon to be released! 

https://github.com/datocms/gatsby-source-datocms/blob/2.1.0/CHANGELOG.md#v210
