### ISSUE TITLE
Why downgrade the lastest release to v1.1.15 ?

### ISSUE THREAD

**Issue by joZephhh** [datocms/gatsby-source-datocms#38]
Hello, 

Is there any reason for the downgrade of the plugin to 1.1.15?  It removes the compatibility to gatsby v2.

Thanks :)

**Comment by stefanoverna** [comment]
hi @joZephhh, could you elaborate please?

**Comment by joZephhh** [comment]
Hello, 

The last release appears to be 1.1.15 (npm and github releases), but 27 days ago a 2.0.1 version has been released. Is there any reason of this downgrade, or it's an error?

<img width="458" alt="" src="https://user-images.githubusercontent.com/17252766/50308264-07464b00-049b-11e9-9249-77dc41abb31f.png">

**Comment by sibiraj-sr** [comment]
@stefanoverna Since Gatsby 2.x is the latest out there. I suggest that v2 of this plugin can be published to latest and v1 can be maintained.

>We simply maintain v1.x.x of this plugin for Gatsby v1,
and v2 for Gatsby v2.

this should have been in README
