### ISSUE TITLE
Special (Unescaped) characters in image urls break build

### ISSUE THREAD

**Issue by vadistic** [datocms/gatsby-source-datocms#40]
Hello,

Special characters in dato-cms image file names break plugin on build :cry: 

It's kind of tricky, because I believe asking my users - please avoid spaces and special characters in file names you upload to DatoCms or the site will break - would not work for very long :smile: 

Not just my machine - CI build fails too. What's interesting - development mode works fine.

```
// versions: latest
gatsby: 2.0.118
gatsby-source-datocms: 2.0.1
node 11.8.0
```

```
Errors:
  Request path contains unescaped characters
  
  GraphQL request (23:7)
  22:       id
  23:       fluid(maxWidth: 2000, maxHeight: 1600, imgixParams: {fm: "jpg", auto: "compress"}) {
            ^
  24:         ...GatsbyDatoCmsFluid
  ```

Reproduction
---
For example - in your example gatsby portfolio stater, there is an image used in gallery with url:
```
https://www.datocms-assets.com/604/1481209135-Argö-Poster.jpg
```

Try quering
```
export const WORK_TEMPLATE_QUERY = graphql`
  query WorkQuery($slug: String!) {
      gallery {
        fluid(maxWidth: 2000, maxHeight: 1600, imgixParams: { fm: "jpg", auto: "compress" }) {
          ...GatsbyDatoCmsFluid
        }
    }
  }
`
```

**Comment by shenst1** [comment]
Currently getting this issue in the portfolio demo project as well.

**Comment by matjack1** [comment]
I can replicate and confirm also with newer versions:

- Gatsby 2.4.3
- gatsby-source-datocms 2.1.4

**Comment by matjack1** [comment]
@vadistic @shenst1 not sure if you can or if you are still interested in this, but can you please confirm that this happens only on Node v11? I've reproduced with that version, but using `v9.11.2` works fine here.

Thank you!

**Comment by matjack1** [comment]
OK, I was able to consistently get the error and I've fixed with this: https://github.com/datocms/gatsby-source-datocms/pull/57

If you could confirm it would be grea!

**Comment by matjack1** [comment]
I've merged the relevant PR. I'm going to close this now, but feel free to reopen if you need to.
