### ISSUE TITLE
Surface createdAt and publishedAt values

### ISSUE THREAD

**Issue by seancdavis** [datocms/gatsby-source-datocms#41]
I've noticed that you have surfaced an item's `_updatedAt` response to `updatedAt`. I'm wondering how we can also get access to `_createdAt` and `_publishedAt` fields?

I figured adding `createdAt` below [this line](https://github.com/datocms/gatsby-source-datocms/blob/a4bb1650da2da4317f68098a8a2805c010b95544/src/createItemNodes.js#L103) would work fine:

```js
itemNode.createdAt = item.createdAt;
```

And that seems to work fine. But the same is not true for `publishedAt`. I know this is a value that has to be enabled in the API, but even attempting with models that have this feature enabled does not surface the option.

I'm happy to submit a PR, but curious to get your thoughts on the matter and some direction first.

**Comment by stefanoverna** [comment]
Solved in version `2.1.0-beta.1`, soon to be released! 

https://github.com/datocms/gatsby-source-datocms/blob/2.1.0/CHANGELOG.md#v210
