### ISSUE TITLE
Fluid images: base64 always undefined

### ISSUE THREAD

**Issue by wappsify** [datocms/gatsby-source-datocms#42]
I noticed using `gatsby-image` with fluid images provided by this plugin does not work correctly right now. 

This seems to be due to `gatsby-source-datocms` returning `undefined` as ` base64` for all images when querying for their fluid data. 
This seems to have broken recently?

**Comment by stefanoverna** [comment]
Yes, please upgrade to the latest version of this plugin to see it solved!

Il giorno gio 14 feb 2019, 16:44 Yannik Wissner <notifications@github.com>
ha scritto:

**Comment by wappsify** [comment]
Thanks, this fixed it!
