### ISSUE TITLE
Replacement for inlineSvg?

### ISSUE THREAD

**Issue by seancdavis** [datocms/gatsby-source-datocms#46]
It looks like as of 2.1, you've removed support for the `inlineSvg` attribute. [The release blog post](https://www.datocms.com/blog/blazing-fast-development-with-gatsby-and-datocms) mentions that you were wanting to maintain backwards compatibility, but there doesn't seem to be a quick replacement for this feature.

Do you have a recommendation on how we should work with SVG images moving forward?

**Comment by matjack1** [comment]
@seancdavis yes, there's no more the `inlineSvg` attribute, but it's always been an undocumented feature that we have decided to remove as we thought it wasn't a good idea, in particular performance-wise.

We might introduce it again but we don't recommend it right now. I guess you should simply use SVG images without inlining them? Or do you have a specific use case in mind?

I'm going to close for now, but feel free to comment further if you wish.
