### ISSUE TITLE
Linked fields don't work for any locale with a dash (-), such as zh-CN

### ISSUE THREAD

**Issue by anthonysapp** [datocms/gatsby-source-datocms#55]
Any linked field with a locale that has a dash in it will return **null**.

Example: 
- Add the locale zh-CN to your project
- Create a singleton model with a linked field
- Open the content editor and set that linked field to another item

Query the api and that linked field will always return **null** 

Tested this with multiple locales with dashes - same result. 
Re-tested same scenario with locale without a dash - returns correct linked field.

**Comment by matjack1** [comment]
yes @anthonysapp I could reproduce with an older version of our `datocms-client` package.

We've recently updated it to 1.0.4 which should solve the problem. Can you please make sure that's the version installed as a dependency of `gatsby-source-datocms` and let me know if the problem is solved?

**Comment by anthonysapp** [comment]
Confirming this works! Thanks for the quick reply :) Closing.

**Comment by matjack1** [comment]
Awesome, thanks!
