### ISSUE TITLE
Gatsby v3 Build Warnings

### ISSUE THREAD

**Issue by brohlson** [datocms/gatsby-source-datocms#58]
Gatsby Version: 2.7.1
Plugin Version: 2.1.5

New warning being thrown with the lastest verision of the plugin at build time:
`adding inferred resolver for field DatoCmsAsset.createdAt. In Gatsby v3, only fields with an explicit directive/extension will get a resolver`

**Comment by matjack1** [comment]
Thank you for reporting this, we surely need to address this warning as soon as possible

**Comment by matjack1** [comment]
This is now fixed in master, we'll release on NPM next week.
