### ISSUE TITLE
No favicon in Dato results in build error

### ISSUE THREAD

**Issue by marcelkalveram** [datocms/gatsby-source-datocms#6]
Hi, I didn't have any favicon uploaded to Dato in my global site settings and got this error when running `gatsby develop`.

```GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `rel` on type `attributes_4`. Source: document `GatsbyDatoCmsFaviconMetaTags` file: `GraphQL request`.
```

I can upload a favicon to resolve this issue, but thought I'd point it out regardless as people who are new to Gatsby, Dato or this plugin might have trouble with this.

**Comment by drobinhood** [comment]
I was having the same issue as @marcelkalveram.

**Comment by dardub** [comment]
Ya Gatsby currently throws that error if you have inconsistent or missing data in your query. If just one record has missing data, it will randomly fail.

**Comment by marcelkalveram** [comment]
Just submitted a PR https://github.com/datocms/gatsby-source-datocms/pull/9 that should resolve the issue. At least it did for me.

**Comment by stefanoverna** [comment]
It's still a temporary solution.. but for now we'll go with it. Thanks @marcelkalveram!
