### ISSUE TITLE
Crop not working for fluid gatsby-image

### ISSUE THREAD

**Issue by iljapanic** [datocms/gatsby-source-datocms#60]
**Description of the issue:**
Fluid images queried via grapqhl are not being cropped when both ``maxWidth`` and ``maxHeight`` are defined.

**Relevant snippet:**
```grapqhl
fluid(maxWidth: 450, maxHeight: 500, imgixParams: { fm: "jpg", auto: "compress" }) {
    ...GatsbyDatoCmsFluid
}
```
(I've tried messing with imgix parameters as well to no avail.)

**Issue preview:**
<img width="1035" alt="screenshot_2019-05-30_13-38-07" src="https://user-images.githubusercontent.com/1295321/58630625-472e1b80-82e0-11e9-9d6f-990c902826c0.png">
<img width="685" alt="screenshot_2019-05-30_13-38-17" src="https://user-images.githubusercontent.com/1295321/58630626-472e1b80-82e0-11e9-96d4-6c6291c788a7.png">

The issue only affects images from the datocms source plugin. If you look at the Instagram images on the bottom of the front page you can see cropping is working (I have tested non-square ratios to check)

Cropping was working fine when I was using version ``2.0.2`` of the plugin and only showed up when I have upgraded to the latest version.

**Environment:**
- node _10.15.3_
- gatsby _2.7.5_
- gatsby-source-datocms *2.1.5*

**Comment by iljapanic** [comment]
I have just tried with ``2.0.2`` and it works as expected:

<img width="1062" alt="screenshot_2019-05-30_14-03-05" src="https://user-images.githubusercontent.com/1295321/58631714-b48f7b80-82e3-11e9-8968-d5bde083a074.png">

**Comment by matjack1** [comment]
Hey @iljapanic sorry for the delay here :(

If you pass maxWidth it will ignore the maxHeight, but I can reproduce that maxHeight gets ignored.

Also, since it's a fluid image, wouldn't make sense to ignore one or the other?

**Comment by stefanoverna** [comment]
@matjack1 we'll check if maxHeight gets ignored.
@iljapanic I'm sorry but I'm not sure I understand, can you elaborate? What's the value of the `srcset` for both 2.0.2 and 2.1.5?

**Comment by iljapanic** [comment]
@stefanoverna  @matjack1 

[A preview of the site using **2.0.2**](https://lisis.cz/kameny/) (images not skewed)

[A preview of the site using **2.1.11**](https://test--lisis.netlify.com/kameny/) (images skewed)

The only difference between the sites is the version of `gatsby-source-datocms``, every single line of code it otherwise identical.


### `srcset` snippets:

**2.0.2**
```html
<img sizes="(max-width: 450px) 100vw, 450px" srcset="https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=126&amp;w=113 113w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=250&amp;w=225 225w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=500&amp;w=450 450w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=750&amp;w=675 675w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=1000&amp;w=900 900w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=1500&amp;w=1350 1350w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fit=crop&amp;fm=jpg&amp;h=500&amp;w=450 450w" src="https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress&amp;fm=jpg&amp;h=500&amp;w=450" alt="" loading="lazy" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 1; transition: opacity 500ms ease 0s;">
```


**2.1.11**

```html
<img sizes="(max-width: 450px) 100vw, 450px" srcset="https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=0.05&amp;fm=jpg&amp;w=2560 113w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=0.09&amp;fm=jpg&amp;w=2560 225w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=0.18&amp;fm=jpg&amp;w=2560 450w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=0.27&amp;fm=jpg&amp;w=2560 675w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=0.36&amp;fm=jpg&amp;w=2560 900w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=0.53&amp;fm=jpg&amp;w=2560 1350w,
https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;dpr=1&amp;fm=jpg&amp;w=2560 2560w" src="https://www.datocms-assets.com/7350/1540746566-fluorite.jpg?auto=compress%2Cformat&amp;fm=jpg" alt="" loading="lazy" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; object-fit: cover; object-position: center center; opacity: 1; transition: opacity 500ms ease 0s;">
```

**Comment by dante-blitz** [comment]
I also ran into the same issue with v2.1.11.

Setting maxWidth and MaxHeight does not crop images. I've also reverted back to v2.0.2 and images are now being cropped when maxWidth and maxHeight and specified.

**Comment by matjack1** [comment]
@iljapanic @dante-blitz would this PR: https://github.com/datocms/gatsby-source-datocms/pull/70 make sense for your case?
