### ISSUE TITLE
fallbackSeo image returns null

### ISSUE THREAD

**Issue by iljapanic** [datocms/gatsby-source-datocms#62]
I've updated to 2.1.7 to try out whether it would by some chance resolve my previous issue (#60).

While at it I discovered that the ``image`` field in ``fallbackSeo`` always returns ``null``.

Swapping images in DatoCMS didn't help. All the other fields return data.

I rolled back to 2.0.2 again and ``image`` works fine.

Here in an example query:

```graphql
  datoCmsSite {
    globalSeo {
      siteName
      fallbackSeo {
        description
        image {
          url
        }
      }
    }
  }
```

**Comment by matjack1** [comment]
@iljapanic can you please try again upgrading to latest version of this package and also making sure that you are using datocms-client v2.0.2 by running a `yarn upgrade`?

**Comment by matjack1** [comment]
This: https://github.com/datocms/gatsby-source-datocms/pull/68 should fix your issue, was different from the other one I've highlighted yesterday, sorry!

**Comment by matjack1** [comment]
I'm going to close this as there's no more feedback. But feel free to reopen if the bug still exists.
