### ISSUE TITLE
gatsby develop freezes

### ISSUE THREAD

**Issue by dante-blitz** [datocms/gatsby-source-datocms#63]
Am having issues with gatsby develop once I add gatsby-source-datocms to my project.

Steps to Reproduce

1. Create new gatsby site via gatsby cli
2. 'npm i gatsby-source-datocms'
3. add the following to gatsby-config.js:
```
    {
      resolve: "gatsby-source-datocms",
      options: {
        apiToken: `${process.env.API_KEY}`,
      },
    },
```
4. 'gatsby develop'

Am running Windows 10 with Linux subsysten. Output of gatsby info as follows 

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64        Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.2.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Languages:
    Python: 2.7.15 - /usr/bin/python
  npmPackages:
    gatsby: ^2.8.6 => 2.8.6
    gatsby-image: ^2.1.2 => 2.1.2
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1
    gatsby-plugin-offline: ^2.1.1 => 2.1.1
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3
    gatsby-source-datocms: ^2.1.7 => 2.1.7
    gatsby-source-filesystem: ^2.0.38 => 2.0.38
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21
  npmGlobalPackages:
    gatsby-cli: 2.6.5
```

**Comment by dante-blitz** [comment]
Forgot to mention that 'gatsy develop' works find if i remove datocms plugin from gatsby-config.js

**Comment by dante-blitz** [comment]
Also worth noting that gatsby build works just fine

**Comment by dante-blitz** [comment]
Here's where its getting stuck...

```
success open and validate gatsby-configs - 0.029 s
success load plugins - 4.056 s
success onPreInit - 0.011 s
success initialize cache - 0.075 s
success copy gatsby files - 0.200 s
success onPreBootstrap - 0.023 s
success loading DatoCMS content - 1.140 s
success source and transform nodes - 1.221 s
success building schema - 1.256 s
success createPages - 0.005 s
success createPagesStatefully - 0.095 s
success onPreExtractQueries - 0.011 s
success update schema - 0.040 s
success extract queries from components - 0.146 s
success write out requires - 0.018 s
success write out redirect data - 0.006 s
success onPostBootstrap - 0.003 s
⠀
info bootstrap finished - 14.414 s
⠀
success run static queries - 0.005 s
success run page queries - 0.044 s — 2/2 56.99 queries/second
```

**Comment by matjack1** [comment]
@dante-blitz since it's a bit tricky for the team to test your setup, would you like to do a quick further test with Node v10 rather than v12?

If it's still broken I'll test it myself with your setup.

**Comment by dante-blitz** [comment]
I've switched to nodev10 and its working with one major issue...

'gatsby develop' works the first time its run. Any subsequent attempts to run it do not work. The terminal completely freezes and is unresponsive (same as before). I've tried to kill any gatsby process but cannot. I'm assuming the first develop process doesn't close as it should and this causes issues with any subsequent processes.

The only way for me to get it working again is to restart windows.

**Comment by matjack1** [comment]
@dante-blitz have you tried without the Linux subsystem?

Just checking because I'm not sure we can support also your configuration rigth now, so I'm trying to find alternatives that might just work for you, sorry :(

**Comment by dante-blitz** [comment]
I have switched to plain old Windows without Linux Subsystem and can confirm all is working well.

**Comment by matjack1** [comment]
Excellent, thank you very much.
