### ISSUE TITLE
Regression in v2.1.6 facebookPageUrl no longer exposed on DatoCmsGlobalSeo

### ISSUE THREAD

**Issue by lukaszsamson** [datocms/gatsby-source-datocms#64]
error GraphQL Error Encountered 1 error(s):
- Unknown field 'facebookPageUrl' on type 'DatoCmsGlobalSeo'.

Downgrading to 2.1.5 fixes the issue

**Comment by matjack1** [comment]
@lukaszsamson can you please try upgrading to latest version of this package and also making sure that you are using datocms-client v2.0.2 by running a `yarn upgrade`?

**Comment by lukaszsamson** [comment]
@matjack1 it's fixed, thanks
