### ISSUE TITLE
Create Pages

### ISSUE THREAD

**Issue by joebentaylor** [datocms/gatsby-source-datocms#65]
Hi, create pages seems to only ever create the same page with the same content.

My code:
`
const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)

exports.createPages = ({ graphql, actions }) => {
    const { createPage, createRedirect } = actions

    createRedirect({ fromPath: 'https://mortgagesremortgages.netlify.com/*', toPath: ' https://www.mortgagesrm.co.uk/:splat 301!', isPermanent: true, force: true })

    return new Promise((resolve, reject) => {
        graphql(`
            {
                allDatoCmsNews {
                    edges {
                        node {
                            id
                            title
                            featuredImage {
                                url
                                alt
                            }
                        }
                    }
                }
            }
        `).then(result => {
            result.data.allDatoCmsNews.edges.map(({ node: newsPost }) => {
                const str = newsPost.title;
                const url = str.replace(/\s+/g, '-').toLowerCase();
                createPage({
                    path: `news/${url}`,
                    component: path.resolve(`./src/templates/news-post.jsx`),
                    context: {
                        slug: url,
                    },
                })
            })
            resolve()
        })
    })
}`

Im not sure whats going on

bit if you go to:

www.mortgagesrm.co.uk/news

Click any of the news posts. you get put back into the same one regardless of which you choose.

**Comment by matjack1** [comment]
@joebentaylor looks like you sorted this one out. I'm going to close this, but if I'm wrong feel free to reopen.
