### ISSUE TITLE
Unhandled Rejection: Type with name "DatoCmsTextNode" does not exists

### ISSUE THREAD

**Issue by ericsolberg** [datocms/gatsby-source-datocms#66]
I'm creating a Gatsby project using Dato CMS. It is awesome by the way- excellent product and a very good Gatsby plugin to support it.

I am having a problem that has come up a few times now. This happens after I've made changes to the Dato data model. The error output is long, but this seems to be the relevant part:

```
... During the Gatsby static gen ...
success loading DatoCMS content - 2.400 s
success source and transform nodes - 2.470 s
error UNHANDLED REJECTION

  Error: Type with name "DatoCmsTextNode" does not exists
  
  - TypeStorage.js:44 SchemaComposer.get
    [MyProject]/[graphql-compose]/lib/TypeStorage.js:44:13
... more stack trace
```

In one case, I found a Modular Section that seemed to be the problem. By creating a dummy record for it (because I wasn't currently using that section) it seemed to fix the problem. Later, it seems the problem went away and I was able to remove the dummy record. Now I've just added several new modular section types (without changing any data) and I've got this error again. I'm using trial and error to see if creating dummy records will fix the error, but I thought I'd check here if this is a know issue, or make you aware of it. Or perhaps I'm just doing something wrong?

It doesn't seem to be related to my queries, as I get this even if I remove my queries. I also tried `gatsby clean` which didn't help either.

Oh I didn't just add new modular section types, I deleted a few too (but they weren't in use). I also published all data changes.

Thanks.

**Comment by matjack1** [comment]
hey @ericsolberg are you using the latest version of the plugin?

If so, can you please send at support@datocms.com the project that is having the issue so that I can have a better look?

Thank you!

**Comment by ryanditjia** [comment]
I was getting the same error, after an hour of trial and error, I was able to fix it by removing `node_modules` and `package-lock.json` and then `npm install`. Man, this npm thing feels brittle 😅

**Comment by matjack1** [comment]
thank you for the feedback @ryanditjia 

Doing what you did fixed the problem as I think we have released a fix in a dependency of this source plugin that fixed your issue.

Happy that works now, but sorry for the time waster :(

**Comment by philonor** [comment]
@matjack1 We had the same issue after creating a new model with a modular content block within DatoCMS. After creating the first model item, it was gone. Removing `node_modules` and redoing `npm install` did not help.

**Comment by matjack1** [comment]
@philonor can you please try upgrading to the latest version of our plugin and check also that datocms-client, a dependency of the plugin, is at the latest version by running `npm upgrade`?

If the problem persist please let me know at support@datocms.com
