### ISSUE TITLE
Regression: Field "root" is not defined on tree filter

### ISSUE THREAD

**Issue by anthonysapp** [datocms/gatsby-source-datocms#67]
In newer versions of the plugin, when I query a tree node as is described in the README, like this:
```js
allDatoCmsThing(filter: { root: { eq: true } }) { ... }
```
I'm getting an error like: 
`Field "root" is not defined by type DatoCmsThingFilterInput` 

Reverting to version 2.1.5 fixed this for me, but not 100% sure which version caused the error.

**Comment by matjack1** [comment]
Yes, sorry I can reproduce the error, we'll get back to you as soon as possible. Thank you for reporting this.

**Comment by matjack1** [comment]
@anthonysapp this should be fixed in just released v2.1.13

Thank you for the report and sorry for the problem.
