### ISSUE TITLE
Error #85901 GRAPHQL

### ISSUE THREAD

**Issue by marcinsydor** [datocms/gatsby-source-datocms#72]
I'm not able to run gatsby with `2.13.3` version. 
I might be wrong but there was the same issue in contentful plugin and it was related to `query` in fragments 
https://github.com/gatsbyjs/gatsby/issues/15344#issuecomment-508426164

**Comment by matjack1** [comment]
Hello,

I've just tried with Gatsby `v2.13.3` and our source plugin `v2.1.13` and I cannot reproduce, sorry :(

Can you put together a minimal example that will prove your point? Maybe the problem is in another package?

**Comment by marcinsydor** [comment]
Thanks for sending the path, in case someone has the same issue, removing operation names from queries make made my project work again.
