### ISSUE TITLE
seoMetaTags don't contain global site suffix

### ISSUE THREAD

**Issue by philonor** [datocms/gatsby-source-datocms#76]
In [this article](https://www.datocms.com/docs/static-generators/other-ssg/seo) it sounds like the global seo title suffix should be part of the actual seo tags.

**Actual result**:
Selecting the following results in page titles **without** suffix defined in DatoCMS global seo settings.
```
query MyQuery {
  datoCmsPage {
    seoMetaTags {
      id
      tags
    }
  }
}
```

**Expected result**
Should contain DatoCMS global seo title suffix as in 
```
query MyQuery {
  datoCmsSite(locale: {eq: "de"}) {
    globalSeo {
      titleSuffix
    }
  }
}
```

If this is the expected behavior, how would you adapt the invocation of or the `HelmetDatoCms` to contain the title suffix?

**Comment by matjack1** [comment]
hello @philonor, I've tried to replicate it myself, but works fine here.

Here's my query:

```
{
  datoCmsSite {
    globalSeo {
      titleSuffix
    }
  }
  allDatoCmsBlog {
    nodes {
      seoMetaTags {
        tags
      }
      seo {
        title
      }
    }
  }
}
```

and here's an extract of the result:

```
{
  "data": {
    "datoCmsSite": {
      "globalSeo": {
        "titleSuffix": " - DatoCMS"
      }
    },
    "allDatoCmsBlog": {
      "nodes": [
        {
          "seoMetaTags": {
            "tags": [
              {
                "tagName": "title",
                "content": "Blog - DatoCMS"
              },
              ...
            ]
          },
          "seo": {
            "title": "Blog"
          }
        }
      ]
    }
  }
}
```

Is that what is not working as expected in your case? If it is, can you please send over at support@datocms.com the project URL so that I can try to replicate it myself?

**Comment by matjack1** [comment]
This is now changed. I'm closing this, but let me know if you have any further issue.
