### ISSUE TITLE
GatsbyDatoCmsFixed_tracedSVG fragment requires gatsby-plugin-sharp as a dependency

### ISSUE THREAD

**Issue by wildpow** [datocms/gatsby-source-datocms#79]
If I try and use the `GatsbyDatoCmsFixed_tracedSVG` fragment without `gatsby-image-sharp` added as a dependency I get this error:
```
Errors:
  Cannot find module 'gatsby-plugin-sharp'
  Require stack:
...
```
I was planning to submit a PR to the readme noting this requirement in the gatsby-image section but, first wanted to make sure this isn't just an oversight in the package. Maybe by adding `gatsby-plugin-sharp` as a dependency. 

Either way, I would love to help. Trying to get my 4 PR's for my Hacktoberfest t-shirt :-)

**Comment by matjack1** [comment]
yes please @wildpow ! That looks good to me :)

**Comment by wildpow** [comment]
What do you think @matjack1 ?
https://github.com/datocms/gatsby-source-datocms/pull/80

**Comment by matjack1** [comment]
Merged, enjoy your Hacktoberfest :P
