### ISSUE TITLE
This plugin doesn't build with Gatsby bigger than 1.9.166

### ISSUE THREAD

**Issue by andresgutgon** [datocms/gatsby-source-datocms#8]
Hi,
I was updating dependencies and when I put a Gatsby version bigger than `1.9.166` with version `1.0.17` of this plugin and I do: `yarn build` I get
![image](https://user-images.githubusercontent.com/49499/35481556-3669efe8-0426-11e8-8854-e81d86204c32.png)

I looks like a Babel issue

I think the changes were introduced here:
https://github.com/akadop/gatsby/pull/95

**Comment by Demeny** [comment]
I'm getting the same issue.

**Comment by marcelkalveram** [comment]
+1

I had to remove the `HelmetDatoCms` plugin which was generating the favicon in my case:
`<HelmetDatoCms favicon={data.datoCmsSite.faviconMetaTags} />`

**Comment by marcelkalveram** [comment]
I resolved it by adding the following `.babelrc` file to the root of the plugin:

```
{
  "presets": [
    "es2015",
    "react"
  ]
}
```

This compiles the ES6 to ES5, which you can verify by running `npm run build` inside the plugin directory. This made the Uglify compiler error go away for me.

**Comment by stefanoverna** [comment]
What version of nodejs are you using?

**Comment by andresgutgon** [comment]
Honestly I'm not sure if I was in the right `node` version when I got this error. Maybe I was on `v6`, but I'm developing the project in `8.1.4`. I want to try againg and try also @marcelkalveram  solution.

**Comment by marcelkalveram** [comment]
I recently updated my node version to 9.4.0

**Comment by stefanoverna** [comment]
v1.0.26 should solve your problem! 👍 thanks for the report!
