### ISSUE TITLE
DatoCmsAsset and DatoCmsFileField

### ISSUE THREAD

**Issue by SntsDev** [datocms/gatsby-source-datocms#81]
Hello,
At some point in time a change was done that now creates a problem: Before, I was using `onCreateNode` to add fields to a type `DatoCmsAsset` record or to create a local copy. 

Now, when I make the query of, for instance, a **picture** that should be of that type (`DatoCmsAsset`) it provides a `DatoCmsFileField` field instead, which doesn't contain the added fields. Therefore, my code is now reporting missing fields and I'm not being able to build.

Is this a bug? Should I stay with past versions of Gatsby / Gatsby-Source-Datocms ? Should I stop using Gatsby-Source-Datocms and make queries to the API instead?

<img width="300" alt="Captura de pantalla 2019-10-12 a las 0 05 48" src="https://user-images.githubusercontent.com/4103411/66687876-a5064300-ec84-11e9-8dcc-20b9275ddfa6.png">

Or perhaps you could just copy the children (fields) of `DatoCmsAsset` into `DatoCmsFileField`.

**Comment by matjack1** [comment]
@SntsDev have you tried adding the fields directly to the `DatoCmsFileField`?

We have switched to this in order to map the changes we did in the Media Area: https://www.datocms.com/blog/our-new-media-area-is-online

Let me knof if I've missed something in your message instead

**Comment by SntsDev** [comment]
Hi @matjack1 , yes, I've tried. 
I'm doing this programmatically, not on DatoCMS new Media Area UI.
However, on `onCreateNode` there isn't access to `DatoCmsFileField`, only to `File`, `ImageSharp` or `DatoCmsAsset`. If I add it to `File` I don't get the fields on `DatoCmsFileField`. 
How do you suggest to do it? Make a `createResolvers`?
Thanks.

**Comment by SntsDev** [comment]
Hi again @matjack1, I solved this with `createResolvers`, adding dynamically a new property in `DatoCmsFileField`.

**Comment by matjack1** [comment]
excellent, thanks for the feedback!
