### ISSUE TITLE
Schema Names don't match files

### ISSUE THREAD

**Issue by tbrannam** [datocms/gatsby-source-datocms#83]
DatoCmsSeoMetaTags / DatoCmsTextNode fieldType definitions and their file names seem to be swapped.

https://github.com/datocms/gatsby-source-datocms/blob/d53b45ab129dad3dabf6db5d32444fa428eca1af/src/hooks/sourceNodes/createTypes/fieldTypes/DatoCmsTextNode.js#L4

**Comment by matjack1** [comment]
thank you! We'll fix this, you are right!

**Comment by stefanoverna** [comment]
Fixed in upcoming 2.1.21!
