### ISSUE TITLE
I can't seem to figure out how to order items by position

### ISSUE THREAD

**Issue by anderskitson** [datocms/gatsby-source-datocms#88]
In the dato API Explorer I can order posts by position like so

```
query MyQuery {
  allProjects(orderBy: position_ASC) {
    slug
  }
}
```

However in Gatsby the same query alludes me I have tried something like this below but it gives me this error `Expected type SortOrderEnum, found position_ASC`

```
query MyQuery {
  allDatoCmsProject(sort: {order: position_ASC}) {
    edges {
      node {
        slug
      }
    }
  }
}

```

**Comment by wispyco** [comment]
I have a more detailed question on stackoverflow https://stackoverflow.com/questions/59603233/attempting-to-sort-graphql-order-by-position-with-datocms-adn-gatsby-js

**Comment by stefanoverna** [comment]
Replied on SO!
