### ISSUE TITLE
Img base64 blur quality

### ISSUE THREAD

**Issue by dbismut** [datocms/gatsby-source-datocms#95]
Hi, is it me or is the quality of the base64 blurred image used as a placeholder a lot poorer than the one from the native api?

I’m not sure I understand the code correctly but wouldn’t it be simpler to query the blurred image generated by the native api rather than the code in the resizeUrl file?

Sorry if this is silly.

**Comment by stefanoverna** [comment]
Hey @dbismut! Yes I can confirm the way placeholders are generated is different between the Gatsby plugin and our GraphQL API. The Gatsby plugin was built before our `responsiveImage` query even existed. We might try to convert the logic now that we have it.

**Comment by stefanoverna** [comment]
Now blurred images use the same blurhash technique as our Content Delivery API!
