### ISSUE TITLE
Gatsby Fluid Image - not generating proper width parameters with Dato?

### ISSUE THREAD

**Issue by vsimak** [datocms/gatsby-source-datocms#99]
I might be completely on the wrong bananas, but I tested everything aside going within the lib to see whats happening.

If I understand correctly, the gatsby-image fluid together with DatoCms would ask Dato's API to generate different sizes for each width via parameter.
But what I see is that, not only it is not responsive, but it also ignored the maxWidth graphql filter.

The question is also from where is it generating the 3024px.

![image](https://user-images.githubusercontent.com/737041/75441545-26bdeb00-595e-11ea-946f-2da821618d3e.png)

![image](https://user-images.githubusercontent.com/737041/75440967-11948c80-595d-11ea-9071-f1dd573a9a37.png)

"gatsby": "^2.19.12",
"gatsby-image": "^2.2.40",
"gatsby-source-datocms": "^2.1.23",

**Comment by matjack1** [comment]
hey @vsimak can you please explain why you think it's not responsive? We are providing the srcset for smaller resolutions and also for bigger ones for denser displays.

The `1200px` is the biggest one, but we provide bigger options for displays with higher pixel density. What would you expect instead?

**Comment by matjack1** [comment]
I'm closing this for lack of feedback, but please reopen if needed!
